apiVersion: v1
kind: ReplicationController
metadata: 
  name: redis-slave
spec:
  replicas: 2
  selector:
    app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: kubeguide/guestbook-redis-slave
        ports:
        - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: env
