apiVersion: v1
kind: Pod
metadata:
  name: frontend-redis
  labels:
    app: frontend-redis
spec:
  containers:
    - name: frontend
      image: kubeguide/guestbook-php-frontend:localredis
      ports:
      - containerPort: 80
    - name: redis
      image: kubeguide/redis-master
      ports:
      - containerPort: 6379
