apiVersion: v1
kind: ReplicationController
metadata: 
  name: alpine-nginx
spec:
  replicas: 2
  selector:
    app: alpine-ng
  template:
    metadata:
      labels:
        app: alpine-ng
    spec:
      containers:
      - name: alpine-ng
        image: sxlsteven/alpine:nginx1.0.0
        ports:
        - containerPort: 80
