apiVersion: v1
kind: Service
metadata:
  name: busybox-web
  labels:
    app: busybox-web
spec:
  type: NodePort
  selector:
    app: busybox-web
  ports:
  - targetPort: 80
    port: 80
#    nodePort: 9999
