apiVersion: v1
kind: Pod
metadata:
  name: busybox-web
  labels:
    app: busybox-web
spec:
  containers:
  - name: busybox-web
    image: sxlsteven/busybox-web:1.0.1
    ports:
    - containerPort: 80
      hostPort: 8999
