apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS 
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.96.0.10
  ports:
  - name: dns-udp
    port: 53
    protocol: udp
  - name: dns-tcp
    port: 53
    protocol: tcp
