apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: busybox-web
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: busybox-web
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
