apiVersion: v1
kind: Pod
metadata:
  name: healthy-check-tcp
  labels:
    app: healthy-check
spec:
  containers:
  - name: healthy-check
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1
