apiVersion: v1
kind: Pod
metadata:
  name: healthy-check-http
  labels:
    app: healthy-check
spec:
  containers:
  - name: healthy-check
    image: nginx:latest
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /_status/healthz
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1 
