apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace:
    kube-system
  labels:
    k8s-app: fluentd-log
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-log  
  template:
    metadata:
      labels:
        k8s-app: fluentd-log 
      namespace: kube-system
    spec:
      containers:
      - name: fluentd-log
        image: ist0ne/fluentd-elasticsearch
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: FLUENTD_ARGS
          value: -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: false
        - name: containers
          mountPath: /data/docker/containers
          readOnly: false
      volumes:
      - name: containers
        hostPath:
          path: /data/docker/containers
      - name: varlog
        hostPath:
          path: /var/log  
