apiVersion: v1
kind: Pod
metadata:
  name: test-app-file
  labels:
    app: test-app-file
spec:
  containers:
  - name: test-app-file
    image: busybox
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:
    - name: serverxml 
      mountPath: /configfiles
  volumes:
  - name: serverxml
    configMap:
      name: cm-appcconf
